from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
import json
from pathlib import Path
import sys
from typing import Any, Iterable

from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_NAMES = (
    "TEST_CATALOGUE.md",
    "COVERAGE_MATRIX.md",
    "RELEASE_GATES.md",
    "TEST_DEBT.md",
    "MILESTONE_TEST_PLAN.md",
)
NOTICE = "<!-- GENERATED by tools/generate_test_catalogue.py. DO NOT EDIT. -->"
RISK_ORDER = {f"R{level}": level for level in range(5)}


class CatalogueError(RuntimeError):
    pass


@dataclass(frozen=True)
class CatalogueContext:
    root: Path
    cases: tuple[dict[str, Any], ...]
    active_milestone: dict[str, Any]
    packages: dict[str, dict[str, Any]]
    source_count: int


def read_object(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise CatalogueError(
            f"{path.as_posix()}: invalid JSON at line {error.lineno}, "
            f"column {error.colno}: {error.msg}"
        ) from error
    if not isinstance(value, dict):
        raise CatalogueError(f"{path.as_posix()}: top-level JSON value must be an object")
    return value


def field_path(parts: Iterable[object]) -> str:
    result = "$"
    for part in parts:
        result += f"[{part}]" if isinstance(part, int) else f".{part}"
    return result


def relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def load_context(
    root: Path = ROOT,
    *,
    schema_root: Path | None = None,
) -> CatalogueContext:
    root = root.resolve()
    schema_path = (schema_root or root / "schemas") / "test-catalogue.schema.json"
    schema = read_object(schema_path)
    Draft202012Validator.check_schema(schema)
    validator = Draft202012Validator(schema)
    diagnostics: list[str] = []
    cases: list[dict[str, Any]] = []
    declared_at: dict[str, str] = {}
    catalog_paths = sorted((root / "tests" / "catalog").glob("*.json"))
    if not catalog_paths:
        diagnostics.append("tests/catalog: no structured catalogue sources found")

    for path in catalog_paths:
        data = read_object(path)
        for error in sorted(
            validator.iter_errors(data),
            key=lambda item: tuple(str(part) for part in item.absolute_path),
        ):
            diagnostics.append(
                f"{relative(root, path)}:{field_path(error.absolute_path)}: {error.message}"
            )
        for index, case in enumerate(data.get("cases", [])):
            if not isinstance(case, dict):
                continue
            case_id = case.get("id")
            if isinstance(case_id, str):
                location = f"{relative(root, path)}:$.cases[{index}].id"
                if case_id in declared_at:
                    diagnostics.append(
                        f"{location}: duplicate test id {case_id}; "
                        f"first declared at {declared_at[case_id]}"
                    )
                else:
                    declared_at[case_id] = location
            cases.append(case)

    milestone_paths = sorted((root / "planning" / "milestones").glob("*.json"))
    milestones = [read_object(path) for path in milestone_paths]
    active = [milestone for milestone in milestones if milestone.get("status") == "ACTIVE"]
    if len(active) != 1:
        diagnostics.append(
            "planning/milestones: expected exactly one ACTIVE milestone, "
            f"found {len(active)}"
        )
    active_milestone = active[0] if active else {}
    packages: dict[str, dict[str, Any]] = {}
    for milestone in milestones:
        for package in milestone.get("work_packages", []):
            if isinstance(package, dict) and isinstance(package.get("id"), str):
                packages[package["id"]] = package

    for case in cases:
        case_id = str(case.get("id", "<unknown>"))
        raw_implementation = case.get("implementation", {})
        implementation = raw_implementation if isinstance(raw_implementation, dict) else {}
        raw_paths = implementation.get("test_paths", [])
        paths = raw_paths if isinstance(raw_paths, list) else []
        for test_path in paths:
            candidate = (root / str(test_path)).resolve()
            if not candidate.is_relative_to(root) or not candidate.is_file():
                diagnostics.append(
                    f"test {case_id}: implementation path does not exist: {test_path}"
                )
        if implementation.get("status") == "automated" and not paths:
            diagnostics.append(f"test {case_id}: automated case has no implementation path")
        case_status = case.get("status")
        implementation_status = implementation.get("status")
        if case_status in {"automated", "manual"} and implementation_status != case_status:
            diagnostics.append(
                f"test {case_id}: case status {case_status} does not match "
                f"implementation status {implementation_status}"
            )
        raw_package_refs = case.get("work_package_refs", [])
        package_refs = raw_package_refs if isinstance(raw_package_refs, list) else []
        for package_id in package_refs:
            if package_id not in packages:
                diagnostics.append(
                    f"test {case_id}: missing work package reference {package_id}"
                )

    case_ids = {str(case.get("id")) for case in cases}
    for package in active_milestone.get("work_packages", []):
        if not isinstance(package, dict):
            continue
        for test_id in package.get("acceptance", []):
            if test_id not in case_ids:
                diagnostics.append(
                    f"package {package.get('id')}: missing catalogue case {test_id}"
                )

    if diagnostics:
        raise CatalogueError("\n".join(sorted(set(diagnostics))))
    return CatalogueContext(
        root=root,
        cases=tuple(sorted(cases, key=lambda case: str(case["id"]))),
        active_milestone=active_milestone,
        packages=packages,
        source_count=len(catalog_paths),
    )


def markdown(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def codes(values: Iterable[object]) -> str:
    rendered = [f"`{markdown(value)}`" for value in sorted({str(value) for value in values})]
    return ", ".join(rendered) if rendered else "—"


def generated_header(title: str) -> list[str]:
    return [
        NOTICE,
        "",
        f"# {title}",
        "",
        "> Source: `tests/catalog/*.json`. Regenerate with "
        "`uv run python tools/generate_test_catalogue.py`.",
        "",
    ]


def counter_line(label: str, values: Iterable[str]) -> str:
    counts = Counter(values)
    rendered = ", ".join(f"`{key}` {counts[key]}" for key in sorted(counts))
    return f"- {label}: {rendered or 'none'}"


def render_catalogue(context: CatalogueContext) -> str:
    lines = generated_header("Test Catalogue")
    lines.extend(
        [
            f"{len(context.cases)} cases from {context.source_count} structured source file(s).",
            "",
            "## Summary",
            "",
            counter_line("Status", (str(case["status"]) for case in context.cases)),
            counter_line("Risk", (str(case["risk"]) for case in context.cases)),
            counter_line(
                "Domain",
                (str(domain) for case in context.cases for domain in case.get("domains", [])),
            ),
            "",
            "## Cases",
            "",
            "| ID | Title | Domains | Risk | Status | Priority | Owner | Implementation |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    ordered = sorted(
        context.cases,
        key=lambda case: (
            str(case.get("domains", [""])[0]),
            -RISK_ORDER.get(str(case.get("risk")), -1),
            str(case.get("status")),
            str(case.get("id")),
        ),
    )
    for case in ordered:
        implementation = case["implementation"]
        lines.append(
            "| {id} | {title} | {domains} | {risk} | {status} | {priority} | "
            "{owner} | {implementation} |".format(
                id=codes([case["id"]]),
                title=markdown(case["title"]),
                domains=codes(case["domains"]),
                risk=codes([case["risk"]]),
                status=codes([case["status"]]),
                priority=codes([case["priority"]]),
                owner=codes([case["owner"]]),
                implementation=codes([implementation["status"]]),
            )
        )
    return "\n".join(lines) + "\n"


def release_gate(case: dict[str, Any]) -> str:
    return "release" if case.get("priority") == "critical" else "—"


def render_coverage(context: CatalogueContext) -> str:
    lines = generated_header("Coverage Matrix")
    lines.extend(
        [
            "Each row links one requirement to its catalogue evidence.",
            "",
            "| Requirement | Test case | Work Packages | Owner | Test paths | Gate |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    rows = []
    for case in context.cases:
        for requirement in case.get("requirement_refs", []):
            rows.append((str(requirement), str(case["id"]), case))
    for requirement, _, case in sorted(rows):
        lines.append(
            f"| {codes([requirement])} | {codes([case['id']])} | "
            f"{codes(case.get('work_package_refs', []))} | {codes([case['owner']])} | "
            f"{codes(case['implementation'].get('test_paths', []))} | "
            f"{codes([release_gate(case)]) if release_gate(case) != '—' else '—'} |"
        )
    return "\n".join(lines) + "\n"


def evidence_state(case: dict[str, Any]) -> str:
    if case.get("waiver"):
        return "waived"
    if case.get("status") in {"automated", "manual"}:
        return "evidence available"
    return "missing evidence"


def render_release_gates(context: CatalogueContext) -> str:
    cases = [
        case
        for case in context.cases
        if case.get("priority") == "critical" and case.get("status") != "retired"
    ]
    lines = generated_header("Release Gates")
    lines.extend(
        [
            "Critical, non-retired cases block the `release` channel unless evidence or an "
            "explicit owner waiver exists.",
            "",
            "| Channel | Test case | Risk | Case status | Implementation | Evidence state |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for case in sorted(cases, key=lambda item: (-RISK_ORDER[item["risk"]], item["id"])):
        lines.append(
            f"| `release` | {codes([case['id']])} | {codes([case['risk']])} | "
            f"{codes([case['status']])} | {codes([case['implementation']['status']])} | "
            f"{markdown(evidence_state(case))} |"
        )
    return "\n".join(lines) + "\n"


def debt_reasons(case: dict[str, Any]) -> list[str]:
    reasons: list[str] = []
    status = case.get("status")
    implementation_status = case.get("implementation", {}).get("status")
    if status == "quarantined" or implementation_status == "quarantined":
        reasons.append("quarantined")
    if status == "specified" or implementation_status == "planned":
        reasons.append("missing automation")
    if case.get("waiver"):
        reasons.append("waiver active")
    if status == "retired" and not case.get("replacement"):
        reasons.append("retired without replacement")
    return sorted(set(reasons))


def render_test_debt(context: CatalogueContext) -> str:
    rows = [(case, debt_reasons(case)) for case in context.cases]
    rows = [(case, reasons) for case, reasons in rows if reasons]
    lines = generated_header("Test Debt")
    lines.extend(
        [
            "Quarantined, waived, retired-without-replacement and not-yet-automated cases.",
            "",
            "| Test case | Risk | Owner | Debt | Test paths |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    ordered = sorted(
        rows,
        key=lambda item: (-RISK_ORDER[item[0]["risk"]], item[0]["id"]),
    )
    for case, reasons in ordered:
        lines.append(
            f"| {codes([case['id']])} | {codes([case['risk']])} | "
            f"{codes([case['owner']])} | {markdown(', '.join(reasons))} | "
            f"{codes(case['implementation'].get('test_paths', []))} |"
        )
    if not rows:
        lines.extend(["", "No test debt is currently recorded."])
    return "\n".join(lines) + "\n"


def render_milestone_plan(context: CatalogueContext) -> str:
    milestone = context.active_milestone
    case_by_id = {case["id"]: case for case in context.cases}
    packages = [
        package for package in milestone.get("work_packages", []) if isinstance(package, dict)
    ]
    lines = generated_header("Milestone Test Plan")
    lines.extend(
        [
            f"Active milestone: `{markdown(milestone.get('id', 'unknown'))}` — "
            f"{markdown(milestone.get('title', 'untitled'))}.",
            "",
            counter_line("Package status", (str(package["status"]) for package in packages)),
            "",
            "| Work Package | Package status | Acceptance case | Risk | Case status | Owner |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for package in sorted(packages, key=lambda item: str(item["id"])):
        for test_id in sorted(package.get("acceptance", [])):
            case = case_by_id[test_id]
            lines.append(
                f"| {codes([package['id']])} | {codes([package['status']])} | "
                f"{codes([test_id])} | {codes([case['risk']])} | "
                f"{codes([case['status']])} | {codes([case['owner']])} |"
            )
    return "\n".join(lines) + "\n"


def render_views(context: CatalogueContext) -> dict[str, str]:
    return {
        "TEST_CATALOGUE.md": render_catalogue(context),
        "COVERAGE_MATRIX.md": render_coverage(context),
        "RELEASE_GATES.md": render_release_gates(context),
        "TEST_DEBT.md": render_test_debt(context),
        "MILESTONE_TEST_PLAN.md": render_milestone_plan(context),
    }


def synchronize(
    root: Path = ROOT,
    *,
    check: bool = False,
    schema_root: Path | None = None,
) -> list[str]:
    root = root.resolve()
    output_dir = root / "docs" / "testing" / "generated"
    views = render_views(load_context(root, schema_root=schema_root))
    diagnostics: list[str] = []
    existing = set(output_dir.glob("*.md")) if output_dir.exists() else set()
    expected_paths = {output_dir / name for name in OUTPUT_NAMES}

    if check:
        for name, content in views.items():
            path = output_dir / name
            if not path.exists():
                diagnostics.append(f"missing generated test catalogue view: {relative(root, path)}")
            elif path.read_text(encoding="utf-8") != content:
                diagnostics.append(f"stale generated test catalogue view: {relative(root, path)}")
        for path in sorted(existing - expected_paths):
            diagnostics.append(f"unexpected generated test catalogue view: {relative(root, path)}")
        return diagnostics

    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in views.items():
        (output_dir / name).write_text(content, encoding="utf-8", newline="\n")
    for path in existing - expected_paths:
        path.unlink()
    return diagnostics


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        diagnostics = synchronize(check=args.check)
    except CatalogueError as error:
        print(f"Test catalogue generation failed:\n{error}")
        return 1
    if diagnostics:
        print("Test catalogue generated-view check failed:")
        print("\n".join(f"- {diagnostic}" for diagnostic in diagnostics))
        return 1
    verb = "checked" if args.check else "generated"
    print(f"Test catalogue views {verb} ({len(OUTPUT_NAMES)} files).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
